config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy", as: :logout
  get 'register' => "users#new"
  post 'register' => "users#create"
  get 'about' => "about#index", as: :about

  resources :users, except: [:index, :destroy] do
    member do
      patch "collect_course"
      patch "remove_course"
      patch "collect_score"
      patch "remove_score"
    end
  end

  resources :messages

  resources :courses, only: [:show, :index]
  resources :scores, only: [:show, :index]
  resources :comments, only: [:create]
  resources :columns, only: [:index, :show]

  resources :tags, only: [:index, :show]
  resources :photo_shows, only: [:index, :show]

  namespace :admin do
    get 'login' => 'sessions#new', as: :login
    post 'login' => 'sessions#create'
    delete 'login' => 'sessions#destroy'

    get '/' => 'dashboard#index'

    resources 'courses'
    resources 'scores' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'columns' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'users', only: [:index, :create, :new] do
      member do
        get 'frozen'
      end
    end

    resources 'advertisements'

    resources 'comments', only: [:create, :destroy] do
      member do
        patch 'block'
        patch 'unblock'
      end
    end

    resources 'tags'
    resources 'photo_shows'
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  content       :string
#  has_been_read :boolean          default(FALSE)
#  type          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Message < ActiveRecord::Base
  belongs_to :user
  def Message.msg_count(user_id)
    count = Message.where(user_id: user_id, has_been_read: false).to_a.count
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def has_read
    @message = Message.find(params[:msg_id])
    @message.has_read = 't'
    @message.save
    redirect_to @message.link
  end

  def index
    @messages = Message.where(user_id: @current_user.id).order('has_been_read').to_a
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :content, :link, :has_read, :level)
    end
end

app/views/messages/_form.html.slim
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      h2 = "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      ul
        - @message.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :level
    = f.text_field :level
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :link
    = f.text_field :link

  .actions = f.submit

app/views/messages/edit.html.slim
h1 Editing message

== render 'form'

= link_to 'Show', @message
'|
= link_to 'Back', messages_path

app/views/messages/index.html.slim
h3 消息列表

table
  thead
    tr
      th Link
      th Has read
      th
      th

  tbody
    - @messages.each do |message|
      tr
        td = link_to message.content, read_message_path(message, msg_id: message.id)
        td = message.has_read
        td = message.created_at.to_s(:db) 
        td = link_to 'Destroy', message, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/messages/new.html.slim
h1 New message

== render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.slim
p#notice = notice

p
  strong User:
  = @message.user_id
p
  strong Content:
  = @message.content
p
  strong Link:
  = @message.link
p
  strong Has read:
  = @message.has_read
p
  strong Level:
  = @message.level

= link_to 'Edit', edit_message_path(@message)
'|
= link_to 'Back', messages_path