config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy", as: :logout
  get 'register' => "users#new"
  post 'register' => "users#create"
  get 'about' => "about#index", as: :about

  resources :users, except: [:index, :destroy] do
    member do
      patch "collect_course"
      patch "remove_course"
      patch "collect_score"
      patch "remove_score"
    end
  end

  resources :messages

  resources :courses, only: [:show, :index]
  resources :scores, only: [:show, :index]
  resources :comments, only: [:create]
  resources :columns, only: [:index, :show]

  resources :tags, only: [:index, :show]
  resources :photo_shows, only: [:index, :show]

  namespace :admin do
    get 'login' => 'sessions#new', as: :login
    post 'login' => 'sessions#create'
    delete 'login' => 'sessions#destroy'

    get '/' => 'dashboard#index'

    resources 'courses'
    resources 'scores' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'columns' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'users', only: [:index, :create, :new] do
      member do
        get 'frozen'
      end
    end

    resources 'advertisements'

    resources 'comments', only: [:create, :destroy] do
      member do
        patch 'block'
        patch 'unblock'
      end
    end

    resources 'tags'
    resources 'photo_shows'
  end

end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id          :integer          not null, primary key
#  name        :string
#  image_ids   :integer          default([]), is an Array
#  description :string
#  course_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Score < ActiveRecord::Base
  belongs_to :course
  validates :name, presence: true

  def images
    self.image_ids.map do |id|
      Attachment.find(id)
    end
  end

  def is_images_valid(ids)
    ids = ids.map {|i| i.to_i}
    if ids.sort == self.image_ids.sort
      return true
    end
    false
  end

end

app/controllers/admin/scores_controller.rb
class Admin::ScoresController < Admin::ApplicationController
  def index
    @scores = Score.all
  end

  def create
    score = Score.new
    score.name = score_params[:name]
    score.description = score_params[:description]
    score_params[:images].each do |image|
      attachment = Attachment.create(file: image)
      score.image_ids.push attachment.id
    end
    score.save
    redirect_to admin_scores_path
  end

  def show
    @score = Score.find(params[:id])
  end

  def update
    @score = Score.find params[:id]
    @score.name = score_params[:name]
    @score.description = score_params[:description]
    if score_params[:images]
      Attachment.delete @score.image_ids
      @score.image_ids = []
      score_params[:images].each do |image|
        attachment = Attachment.create(file: image)
        @score.image_ids.push attachment.id
      end
    end
    @score.save
    redirect_to admin_scores_path
  end

  def update_images_order
    @score = Score.find params[:id]
    if @score.is_images_valid(params[:ids])
      @score.update_attribute :image_ids, params[:ids]
      @score.save
      head :ok
    else
      head :bad_request
    end
  end

  def destroy
    score = Score.find params[:id]
    Attachment.delete score.image_ids
    score.destroy
    redirect_to admin_scores_path
  end

  def edit
    @score = Score.find params[:id]
  end

  def new
    @score = Score.new
  end

  private
  def score_params
    params.require(:score).permit(:name, :description, images: [])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @scores = Score.all
  end

  def show
    @score = Score.find params[:id]
  end
end

app/views/scores/index.html.slim
.scores.row
  - @scores.each do |score|
    .col-lg-3
      .score
        a href=score_path(score)
          img src=score.images.first.file.url
        .meta = "[#{score.description}]"

app/views/scores/show.html.slim
.score
  h1 = @score.name
  .well = @score.description
  - if login?
    - if current_user.has_collected_score @score.id
      a.btn.btn-danger.btn-lg.remove-score href=remove_score_user_path(current_user) data-method="patch" data-remote="true" data-params="score_id=#{@score.id}" 取消收藏
    - else
      a.btn.btn-info.btn-lg.collect-score href=collect_score_user_path(current_user) data-method="patch" data-remote="ture" data-params="score_id=#{@score.id}" 收藏

  .images.row
    - @score.images.each do |image|
      .col-lg-3
        a.magnific-popup href=image.file.url
          img src=image.file.url

javascript:
  $(".magnific-popup").magnificPopup({
    type: "image",
    closeOnContentClick: true,
    image: {
      verticalFit: true,
    },
  })