config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy", as: :logout
  get 'register' => "users#new"
  post 'register' => "users#create"
  get 'about' => "about#index", as: :about

  resources :users, except: [:index, :destroy] do
    member do
      patch "collect_course"
      patch "remove_course"
      patch "collect_score"
      patch "remove_score"
    end
  end

  resources :messages

  resources :courses, only: [:show, :index]
  resources :scores, only: [:show, :index]
  resources :comments, only: [:create]
  resources :columns, only: [:index, :show]

  resources :tags, only: [:index, :show]
  resources :photo_shows, only: [:index, :show]

  namespace :admin do
    get 'login' => 'sessions#new', as: :login
    post 'login' => 'sessions#create'
    delete 'login' => 'sessions#destroy'

    get '/' => 'dashboard#index'

    resources 'courses'
    resources 'scores' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'columns' do
      member do
        patch 'update_images_order'
      end
    end

    resources 'users', only: [:index, :create, :new] do
      member do
        get 'frozen'
      end
    end

    resources 'advertisements'

    resources 'comments', only: [:create, :destroy] do
      member do
        patch 'block'
        patch 'unblock'
      end
    end

    resources 'tags'
    resources 'photo_shows'
  end

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id             :integer          not null, primary key
#  name        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  cover_image_id     :integer
#

class Tag < ActiveRecord::Base
  has_many :column_tags
  has_many :columns, through: :column_tags
  has_many :course_tags
  has_many :courses, through: :course_tags

  validates :name, presence: true, uniqueness: true

  def Tag.get_all_tags(tag_list)
    if tag_list
      name_list = ""
      tag_list.each do |t|
        name_list = name_list + t.name + " "
      end
      name_list
    end
  end

  def cover_image
    if self.cover_image_id
      Attachment.find(self.cover_image_id)
    end
  end

  def get_cover_image_url
    if self.cover_image_id
      cover_image = Attachment.find(self.cover_image_id)
      url = cover_image.file.url
    else
      url = "images/search/01.jpg"
    end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new
    @tag.name = tag_params[:name]
    if tag_params[:cover_image]
      attachment = Attachment.create(file: tag_params[:cover_image])
      @tag.cover_image_id = attachment.id
    end
    @tag.save
    redirect_to admin_tags_path
  end

  def update
    @tag = Tag.find params[:id]
    @tag.name = tag_params[:name]
    if tag_params[:cover_image]
      Attachment.delete @tag.cover_image_id
      attachment = Attachment.create(file: tag_params[:cover_image])
      @tag.cover_image_id = attachment.id
    end
    @tag.save
    redirect_to admin_tags_path
  end

  def edit
    @tag = Tag.find params[:id]
  end

  def destroy
    @tag = Tag.find params[:id]
    Attachment.delete @tag.cover_image_id
    @tag.destroy
    redirect_to admin_tags_path
  end

  private
    def tag_params
      params.require(:tag).permit(:name, :cover_image)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.first(10)
  end

  def show
    @tag = Tag.find params[:id]
    @columns = @tag.columns
    @courses = @tag.courses
    render 'courses/index'
  end
end

app/views/admin/tags/_form.slim
= form_for([:admin, @tag], html: { class: 'form-horizontal' }) do |f|
  .form-group
    = f.label :name, "标签名称", class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :cover_image, "选择标签封面图片", class: 'control-label col-md-2'
    .col-md-10
      = f.file_field :cover_image, class: 'form-control'

  .form-group
    .col-md-offset-10.col-md-2
      - text = @tag.new_record? ? "提交" : "更新"
      = f.submit text,class: 'btn btn-primary btn-block'

app/views/admin/tags/edit.slim
h1.page-header 编辑标签

= render 'form'

app/views/admin/tags/index.slim
h1.page-header 所有标签

a.btn.btn-block.btn-info href=new_admin_tag_path
  i.fa.fa-plus 添加标签

table.table.text-center
  thead
    tr
      th 名称
      th 封面图片
      th 对应视频
      th 操作
  tbody
    - @tags.each do |tag|
      tr
        th = tag.name
        th 
          - if tag.cover_image
            img src=tag.cover_image.file.url width = 100 height = 100
          - else
            = '还未设置封面图片'
          
        th 
          a href=admin_tag_path(tag) #{tag.name}
        th
          a.btn.edit-tag href=edit_admin_tag_path(tag) 编辑
          | |
          a.btn.remove-tag href=admin_tag_path(tag) data-method="delete" 删除

app/views/admin/tags/new.slim
h1.page-header 添加标签

= render 'form'